##  Registry::HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\Environment

Function global:ADD-PATH()
{
    [Cmdletbinding()]
    param
    (
    [parameter(Mandatory=$True,
    ValueFromPipeline=$True,
    Position=0)]
    [String[]]$AddedFolder
    )

    # Get the current search path from the environment keys in the registry.

    $currentPath=(Get-ItemProperty -Path ‘Registry::HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\Environment’ -Name PATH).Path

    # See if a new folder has been supplied.

    IF (!$AddedFolder)
    { Return ‘No Folder Supplied. $ENV:PATH Unchanged’}

    # See if the new folder exists on the file system.

    IF (!(TEST-PATH $AddedFolder))
    { Return ‘Folder Does not Exist, Cannot be added to $ENV:PATH’ }

    # See if the new Folder is already in the path.

    $SearchStr = $AddedFolder -replace "\\","\\"
    IF ($currentPath -match $SearchStr)
    { Return ‘Folder already within $ENV:PATH’ }

    # Set the New Path

    $NewPath=$currentPath +’;’ + $AddedFolder

    Set-ItemProperty -Path ‘Registry::HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\Environment’ -Name PATH –Value $newPath

    # Show our results back to the world

    Return $NewPath
}

FUNCTION GLOBAL:GET-PATH() 
{
    $currentPath=(Get-ItemProperty -Path ‘Registry::HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\Environment’ -Name PATH).Path
    Return $currentPath
} 

Function global:REMOVE-PATH()
{
    [Cmdletbinding()]
    param
    (
    [parameter(Mandatory=$True,
    ValueFromPipeline=$True,
    Position=0)]
    [String[]]$RemovedFolder
    )
    
    # Escape backslach charcaters in path strings and add ';s separator
    $RemovedFolder = ";"+ $RemovedFolder -replace "\\","\\"

    # Get the Current Search Path from the environment keys in the registry

    $CurrentPath=(Get-ItemProperty -Path ‘Registry::HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\Environment’ -Name PATH).Path

    # See if the new folder exists on the file system.

    IF (!($CurrentPath -match $RemovedFolder))
    { Return ‘Folder Does not Exist in current path, Cannot remove from $ENV:PATH’ }
    
    # Find the value to remove, replace it with $NULL. If it’s not found, nothing will change.

    $NewPath=$CurrentPath –replace $RemovedFolder,$NULL

    # Update the Environment Path

    Set-ItemProperty -Path ‘Registry::HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\Environment’ -Name PATH –Value $newPath

    # Show what we just did

    Return $NewPath

}

Write-host ("Current Path")
Write-Host ("---------------")
GET-PATH

Write-Host
Write-Host ("Adding new folder to path")ADD-PATH -AddedFolder 'C:\Program Files\OpenSSL-Win64\bin'


#Write-Host
#Write-Host ("Remove folder from path")
#REMOVE-PATH -RemovedFolder 'C:\Program Files\OpenSSL-Win64\bin'


# SIG # Begin signature block
# MIIlxAYJKoZIhvcNAQcCoIIltTCCJbECAQExDzANBglghkgBZQMEAgEFADB5Bgor
# BgEEAYI3AgEEoGswaTA0BgorBgEEAYI3AgEeMCYCAwEAAAQQH8w7YFlLCE63JNLG
# KX7zUQIBAAIBAAIBAAIBAAIBADAxMA0GCWCGSAFlAwQCAQUABCCyWM2k3krd61JP
# cVEpPnwVevo/9kNVZGfn4EAHnnyCh6CCC3cwggVQMIIE9qADAgECAhQqGsiYKDwx
# 9dFYNeILlYSdx2UbkzAKBggqhkjOPQQDAjCBnzELMAkGA1UEBhMCR0IxEjAQBgNV
# BAgTCUhhbXBzaGlyZTEUMBIGA1UEBxMLQmFzaW5nc3Rva2UxETAPBgNVBBETCFJH
# MjIgNUpZMRgwFgYDVQQJEw8yNSBQZXRyZWwgQ3JvZnQxFzAVBgNVBAoTDkJlZ2dh
# cndvb2QgTHRkMSAwHgYDVQQDExdCZWdnYXJ3b29kLUVDRFNBLVJvb3RDQTAgFw0y
# MzA0MDQxMzE0MDdaGA8yMDUzMDQwNDEzMDUxNlowgZwxCzAJBgNVBAYTAkdCMRIw
# EAYDVQQIEwlIYW1wc2hpcmUxFDASBgNVBAcTC0Jhc2luZ3N0b2tlMREwDwYDVQQR
# EwhSRzIyIDVKWTEYMBYGA1UECRMPMjUgUGV0cmVsIENyb2Z0MRcwFQYDVQQKEw5C
# ZWdnYXJ3b29kIEx0ZDEdMBsGA1UEAxMUQmVnZ2Fyd29vZC1SU0EtSUNBMDIwggIi
# MA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQDdVBh5PjZSDWeJHIJA0KW4dpyG
# fHcd1WWU7qvkNbi0Th5FyL+jtM9cUlFFtwRg6I9x3hlvgDUsJocUdcjgg53akWp9
# +wjFrL0d9gshH3z4A+X/ixDkLvkUoeeAZEI0nc38AlChPlhh9Y5CmG4AR2zsKqmC
# qcpn7TGHFAgRIL5Orv23q4dRX8+QlHUWxlzZlSee32cEIvtx1apvBo6sHmY/Tz20
# d17TojOh59hLx3fMRIACwOtE5GipCCoPBBwA5e0WMIIfSj9yinxy9J7fmsLBBrjo
# pf/ngxstm5fNLToCjxGN+qRSiRzvO3RL9t1XqQE4L1iuCxwCOEuzAjUW1rk1rTVc
# dAvCBAABw6t6SnZ/xkZB1FTW5s38hx7CgP0qFYC9jQEMr7iT4VtMR48AsAjcZSge
# mOcIGUEJj2xztrnbebVaJVIGIF95ie9F49FkHl8tw3zpEDtct4O9rIQHtfxlQRvK
# hTMD+BZ2Yk6wjIk97udzzq4MMycdA+MO6CL8vJMiSqXsbXnBeMD7YVqssIrI/fFU
# 2VH9ozXSdfeWWaCjedhYKJEYcdmyMR6rqECjQLucpk6kIXbaPHSpAfocHvHRwkjq
# D2eb1apS1VMUO1tt9krc+ZriQX/5nLxrYm57tlFX9gUIlF3oCz9DXFdAvl7oWmww
# NvM/GYaeA63gmoN79wIDAQABo4IBQjCCAT4wDwYDVR0TAQH/BAUwAwEB/zAdBgNV
# HQ4EFgQUm5aW0/M0XqaEmd/ivRKgT+08h/gwHwYDVR0jBBgwFoAU4ByV9VZ1xG3n
# B1fuL+g6NumigRkwDgYDVR0PAQH/BAQDAgGGMIGLBggrBgEFBQcBAQR/MH0wLQYI
# KwYBBQUHMAGGIWh0dHA6Ly9vY3NwLmRlbW8ub25lLmRpZ2ljZXJ0LmNvbTBMBggr
# BgEFBQcwAoZAaHR0cDovL2NhY2VydHMuZGVtby5vbmUuZGlnaWNlcnQuY29tL0Jl
# Z2dhcndvb2QtRUNEU0EtUm9vdENBLmNydDBNBgNVHR8ERjBEMEKgQKA+hjxodHRw
# Oi8vY3JsLmRlbW8ub25lLmRpZ2ljZXJ0LmNvbS9CZWdnYXJ3b29kLUVDRFNBLVJv
# b3RDQS5jcmwwCgYIKoZIzj0EAwIDSAAwRQIhAKhlFGSxvgAH5EyvcMqvFk79vWs3
# btptsN0Zc30Z3aEVAiBzQU2tTz577MGb/RDj+jGnPh59wO4xh7X2iOAolKZ9VjCC
# Bh8wggQHoAMCAQICFCGZ5fEJQVR+j3lLG00PvFiYuOWOMA0GCSqGSIb3DQEBCwUA
# MIGcMQswCQYDVQQGEwJHQjESMBAGA1UECBMJSGFtcHNoaXJlMRQwEgYDVQQHEwtC
# YXNpbmdzdG9rZTERMA8GA1UEERMIUkcyMiA1SlkxGDAWBgNVBAkTDzI1IFBldHJl
# bCBDcm9mdDEXMBUGA1UEChMOQmVnZ2Fyd29vZCBMdGQxHTAbBgNVBAMTFEJlZ2dh
# cndvb2QtUlNBLUlDQTAyMB4XDTIzMDgyMTEyNDMwMFoXDTIzMDgzMTEyNDMwMFow
# gZYxCzAJBgNVBAYTAkdCMRIwEAYDVQQIEwlIYW1wc2hpcmUxFDASBgNVBAcTC0Jh
# c2luZ3N0b2tlMREwDwYDVQQREwhSRzIyIDVKWTEYMBYGA1UECRMPMjUgUGV0cmVs
# IENyb2Z0MRcwFQYDVQQKEw5CZWdnYXJ3b29kIEx0ZDEXMBUGA1UEAxMOQmVnZ2Fy
# d29vZCBMdGQwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDOeDjucdNm
# pIJs/C0EqWHPnIAks+Kv7j/FN3pwouwsROIRbsdt3zGHC5QgWF8yYp7355jqbfjT
# 8Sqmf/jD5/HRKkMLFlIzv4yk1sE4O38gslBxlozYdDAJzpAaHI1geyVKeaNvCMF7
# oce45YjrsrgMoHbgJtC6juzdz4CGMUY5zCyKSUCXQtKFPDMOidnxigcHTXLkANCb
# WnfL2XmRUvkhUTsBRp9gTwE8zIa2FmwAq2/Yyh/tBiTQuQd9tE4BGldgFiexu5Mi
# VkRIDD0BVaH6VeOUsIjuWjGsdKjFqWYBxNY3tAbvXiCHp6tdqINZhwduIcSqLAGn
# 77b5yTQhgjWzAgMBAAGjggFbMIIBVzAMBgNVHRMBAf8EAjAAMB0GA1UdDgQWBBRN
# 7hE2ChqVeYjA7bMj6a8PxHHzNjAfBgNVHSMEGDAWgBSblpbT8zRepoSZ3+K9EqBP
# 7TyH+DAOBgNVHQ8BAf8EBAMCBeAwIAYDVR0lAQH/BBYwFAYIKwYBBQUHAwMGCCsG
# AQUFBwMCMIGIBggrBgEFBQcBAQR8MHowLQYIKwYBBQUHMAGGIWh0dHA6Ly9vY3Nw
# LmRlbW8ub25lLmRpZ2ljZXJ0LmNvbTBJBggrBgEFBQcwAoY9aHR0cDovL2NhY2Vy
# dHMuZGVtby5vbmUuZGlnaWNlcnQuY29tL0JlZ2dhcndvb2QtUlNBLUlDQTAyLmNy
# dDBKBgNVHR8EQzBBMD+gPaA7hjlodHRwOi8vY3JsLmRlbW8ub25lLmRpZ2ljZXJ0
# LmNvbS9CZWdnYXJ3b29kLVJTQS1JQ0EwMi5jcmwwDQYJKoZIhvcNAQELBQADggIB
# ADZ2x5kvm7jB4SdWMmHrcv3+aS2DAgY7Z23hnemjTV9PtLTL6IF8K6JtQAo/IiPx
# IvuZLuqPFbUOi66fP2/3ljceBER4uUgRb5aubmOcCubCI2O9vCaW8TN5p9rzG8jb
# Vxlw1ITbu5wMfOTpelDoKgHU5pBg7epBDQ8E+k6BUZ3rjMr184hDBD2Be/Vaz3Lw
# Fd19nNep178UU0Q/zO6DOPGbSgcvnTjQuZOgVvzV0u+oDtClS6dQCyCDejruiHYV
# r0QK0YVQxQHN7vIOZ2JWoYhghIspui/lSe0bgzE+Tl8HFNCSWWry1BBk8UZ3AWYo
# hO0GwW5D7Jokyro1iWQ8wFlwrSknVFykKsPiVPaw0G2KdtM0bprB6RkrrCUI4V4i
# S1Z5k7p28GyfRnEeT6S2xOhqqjl3ygZgdr1pwIg7Cx+DNJDZ8IRFMG8XojokIH/g
# kf+EFPrPQnWa0i+wwCIZtQpxKQIsG8BP4mEE9BKx/A13d+0cgr1vB2L3hAd+xIuJ
# 1D0yM8/NkG7jzLZCvggrAMPVhfQ/ggkB2/9aIAO2qwfcktGDKZ+FSfhVV6waw+ua
# e91OWj7uRu74YmBiq5vwETf3Tr4hckhXzLScYmuNQTUSvmBMcfJuJx0zTwwYOOm/
# 4hKullmTlXWN9cywN494BK29Y24NaO4slTWgjcbwhBNrMYIZozCCGZ8CAQEwgbUw
# gZwxCzAJBgNVBAYTAkdCMRIwEAYDVQQIEwlIYW1wc2hpcmUxFDASBgNVBAcTC0Jh
# c2luZ3N0b2tlMREwDwYDVQQREwhSRzIyIDVKWTEYMBYGA1UECRMPMjUgUGV0cmVs
# IENyb2Z0MRcwFQYDVQQKEw5CZWdnYXJ3b29kIEx0ZDEdMBsGA1UEAxMUQmVnZ2Fy
# d29vZC1SU0EtSUNBMDICFCGZ5fEJQVR+j3lLG00PvFiYuOWOMA0GCWCGSAFlAwQC
# AQUAoHwwEAYKKwYBBAGCNwIBDDECMAAwGQYJKoZIhvcNAQkDMQwGCisGAQQBgjcC
# AQQwHAYKKwYBBAGCNwIBCzEOMAwGCisGAQQBgjcCARUwLwYJKoZIhvcNAQkEMSIE
# INr1vGSe4GJEHlGWzIanbAlTbtRzS5plecOZFikyW0LBMA0GCSqGSIb3DQEBAQUA
# BIIBAHmojHUSrx1CeSpQp48TYM0G40BmRk64nK8SF1k3bH7bqkjWDWAIhOl3hnkf
# DbtFbBsdRypF3hjf4+CNo6xuUJCtmGnqHvq4sSoc7g6f142XXy6KGokHpKgm+utP
# b8GJUKf7biBaFw8XuH4DZ+vinM581WO6buJMbYorOs5cGR3QBJteWVsKJpcPJw87
# ZBEirdDQ+lZxKdp13MpbHejSm4u5NzfbZO3HCgSWZr8ZB3ODq/RrD2yjL6HhfJXh
# J2t069KNPV/Z/N8AzIl5EtzHzrY1oMYTX61C+U3zn7drDGjxugsvfu3xzNF/UifX
# TGHWlZlzpMzMpdwLpDV4MW5mL+ihghdAMIIXPAYKKwYBBAGCNwMDATGCFywwghco
# BgkqhkiG9w0BBwKgghcZMIIXFQIBAzEPMA0GCWCGSAFlAwQCAQUAMHgGCyqGSIb3
# DQEJEAEEoGkEZzBlAgEBBglghkgBhv1sBwEwMTANBglghkgBZQMEAgEFAAQgHRAN
# yDfMZEHJsroTKbYqsTwwHlLHYOJKNYsxr05W4OICEQCeEJmUR3+W4ZP8C9/6NrOG
# GA8yMDIzMDgyMjEwMTkyM1qgghMJMIIGwjCCBKqgAwIBAgIQBUSv85SdCDmmv9s/
# X+VhFjANBgkqhkiG9w0BAQsFADBjMQswCQYDVQQGEwJVUzEXMBUGA1UEChMORGln
# aUNlcnQsIEluYy4xOzA5BgNVBAMTMkRpZ2lDZXJ0IFRydXN0ZWQgRzQgUlNBNDA5
# NiBTSEEyNTYgVGltZVN0YW1waW5nIENBMB4XDTIzMDcxNDAwMDAwMFoXDTM0MTAx
# MzIzNTk1OVowSDELMAkGA1UEBhMCVVMxFzAVBgNVBAoTDkRpZ2lDZXJ0LCBJbmMu
# MSAwHgYDVQQDExdEaWdpQ2VydCBUaW1lc3RhbXAgMjAyMzCCAiIwDQYJKoZIhvcN
# AQEBBQADggIPADCCAgoCggIBAKNTRYcdg45brD5UsyPgz5/X5dLnXaEOCdwvSKOX
# ejsqnGfcYhVYwamTEafNqrJq3RApih5iY2nTWJw1cb86l+uUUI8cIOrHmjsvlmbj
# aedp/lvD1isgHMGXlLSlUIHyz8sHpjBoyoNC2vx/CSSUpIIa2mq62DvKXd4ZGIX7
# ReoNYWyd/nFexAaaPPDFLnkPG2ZS48jWPl/aQ9OE9dDH9kgtXkV1lnX+3RChG4PB
# uOZSlbVH13gpOWvgeFmX40QrStWVzu8IF+qCZE3/I+PKhu60pCFkcOvV5aDaY7Mu
# 6QXuqvYk9R28mxyyt1/f8O52fTGZZUdVnUokL6wrl76f5P17cz4y7lI0+9S769Sg
# LDSb495uZBkHNwGRDxy1Uc2qTGaDiGhiu7xBG3gZbeTZD+BYQfvYsSzhUa+0rRUG
# FOpiCBPTaR58ZE2dD9/O0V6MqqtQFcmzyrzXxDtoRKOlO0L9c33u3Qr/eTQQfqZc
# ClhMAD6FaXXHg2TWdc2PEnZWpST618RrIbroHzSYLzrqawGw9/sqhux7UjipmAmh
# cbJsca8+uG+W1eEQE/5hRwqM/vC2x9XH3mwk8L9CgsqgcT2ckpMEtGlwJw1Pt7U2
# 0clfCKRwo+wK8REuZODLIivK8SgTIUlRfgZm0zu++uuRONhRB8qUt+JQofM604qD
# y0B7AgMBAAGjggGLMIIBhzAOBgNVHQ8BAf8EBAMCB4AwDAYDVR0TAQH/BAIwADAW
# BgNVHSUBAf8EDDAKBggrBgEFBQcDCDAgBgNVHSAEGTAXMAgGBmeBDAEEAjALBglg
# hkgBhv1sBwEwHwYDVR0jBBgwFoAUuhbZbU2FL3MpdpovdYxqII+eyG8wHQYDVR0O
# BBYEFKW27xPn783QZKHVVqllMaPe1eNJMFoGA1UdHwRTMFEwT6BNoEuGSWh0dHA6
# Ly9jcmwzLmRpZ2ljZXJ0LmNvbS9EaWdpQ2VydFRydXN0ZWRHNFJTQTQwOTZTSEEy
# NTZUaW1lU3RhbXBpbmdDQS5jcmwwgZAGCCsGAQUFBwEBBIGDMIGAMCQGCCsGAQUF
# BzABhhhodHRwOi8vb2NzcC5kaWdpY2VydC5jb20wWAYIKwYBBQUHMAKGTGh0dHA6
# Ly9jYWNlcnRzLmRpZ2ljZXJ0LmNvbS9EaWdpQ2VydFRydXN0ZWRHNFJTQTQwOTZT
# SEEyNTZUaW1lU3RhbXBpbmdDQS5jcnQwDQYJKoZIhvcNAQELBQADggIBAIEa1t6g
# qbWYF7xwjU+KPGic2CX/yyzkzepdIpLsjCICqbjPgKjZ5+PF7SaCinEvGN1Ott5s
# 1+FgnCvt7T1IjrhrunxdvcJhN2hJd6PrkKoS1yeF844ektrCQDifXcigLiV4JZ0q
# BXqEKZi2V3mP2yZWK7Dzp703DNiYdk9WuVLCtp04qYHnbUFcjGnRuSvExnvPnPp4
# 4pMadqJpddNQ5EQSviANnqlE0PjlSXcIWiHFtM+YlRpUurm8wWkZus8W8oM3NG6w
# QSbd3lqXTzON1I13fXVFoaVYJmoDRd7ZULVQjK9WvUzF4UbFKNOt50MAcN7MmJ4Z
# iQPq1JE3701S88lgIcRWR+3aEUuMMsOI5ljitts++V+wQtaP4xeR0arAVeOGv6wn
# LEHQmjNKqDbUuXKWfpd5OEhfysLcPTLfddY2Z1qJ+Panx+VPNTwAvb6cKmx5Adza
# ROY63jg7B145WPR8czFVoIARyxQMfq68/qTreWWqaNYiyjvrmoI1VygWy2nyMpqy
# 0tg6uLFGhmu6F/3Ed2wVbK6rr3M66ElGt9V/zLY4wNjsHPW2obhDLN9OTH0eaHDA
# dwrUAuBcYLso/zjlUlrWrBciI0707NMX+1Br/wd3H3GXREHJuEbTbDJ8WC9nR2Xl
# G3O2mflrLAZG70Ee8PBf4NvZrZCARK+AEEGKMIIGrjCCBJagAwIBAgIQBzY3tyRU
# fNhHrP0oZipeWzANBgkqhkiG9w0BAQsFADBiMQswCQYDVQQGEwJVUzEVMBMGA1UE
# ChMMRGlnaUNlcnQgSW5jMRkwFwYDVQQLExB3d3cuZGlnaWNlcnQuY29tMSEwHwYD
# VQQDExhEaWdpQ2VydCBUcnVzdGVkIFJvb3QgRzQwHhcNMjIwMzIzMDAwMDAwWhcN
# MzcwMzIyMjM1OTU5WjBjMQswCQYDVQQGEwJVUzEXMBUGA1UEChMORGlnaUNlcnQs
# IEluYy4xOzA5BgNVBAMTMkRpZ2lDZXJ0IFRydXN0ZWQgRzQgUlNBNDA5NiBTSEEy
# NTYgVGltZVN0YW1waW5nIENBMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKC
# AgEAxoY1BkmzwT1ySVFVxyUDxPKRN6mXUaHW0oPRnkyibaCwzIP5WvYRoUQVQl+k
# iPNo+n3znIkLf50fng8zH1ATCyZzlm34V6gCff1DtITaEfFzsbPuK4CEiiIY3+va
# PcQXf6sZKz5C3GeO6lE98NZW1OcoLevTsbV15x8GZY2UKdPZ7Gnf2ZCHRgB720RB
# idx8ald68Dd5n12sy+iEZLRS8nZH92GDGd1ftFQLIWhuNyG7QKxfst5Kfc71ORJn
# 7w6lY2zkpsUdzTYNXNXmG6jBZHRAp8ByxbpOH7G1WE15/tePc5OsLDnipUjW8LAx
# E6lXKZYnLvWHpo9OdhVVJnCYJn+gGkcgQ+NDY4B7dW4nJZCYOjgRs/b2nuY7W+yB
# 3iIU2YIqx5K/oN7jPqJz+ucfWmyU8lKVEStYdEAoq3NDzt9KoRxrOMUp88qqlnNC
# aJ+2RrOdOqPVA+C/8KI8ykLcGEh/FDTP0kyr75s9/g64ZCr6dSgkQe1CvwWcZklS
# UPRR8zZJTYsg0ixXNXkrqPNFYLwjjVj33GHek/45wPmyMKVM1+mYSlg+0wOI/rOP
# 015LdhJRk8mMDDtbiiKowSYI+RQQEgN9XyO7ZONj4KbhPvbCdLI/Hgl27KtdRnXi
# YKNYCQEoAA6EVO7O6V3IXjASvUaetdN2udIOa5kM0jO0zbECAwEAAaOCAV0wggFZ
# MBIGA1UdEwEB/wQIMAYBAf8CAQAwHQYDVR0OBBYEFLoW2W1NhS9zKXaaL3WMaiCP
# nshvMB8GA1UdIwQYMBaAFOzX44LScV1kTN8uZz/nupiuHA9PMA4GA1UdDwEB/wQE
# AwIBhjATBgNVHSUEDDAKBggrBgEFBQcDCDB3BggrBgEFBQcBAQRrMGkwJAYIKwYB
# BQUHMAGGGGh0dHA6Ly9vY3NwLmRpZ2ljZXJ0LmNvbTBBBggrBgEFBQcwAoY1aHR0
# cDovL2NhY2VydHMuZGlnaWNlcnQuY29tL0RpZ2lDZXJ0VHJ1c3RlZFJvb3RHNC5j
# cnQwQwYDVR0fBDwwOjA4oDagNIYyaHR0cDovL2NybDMuZGlnaWNlcnQuY29tL0Rp
# Z2lDZXJ0VHJ1c3RlZFJvb3RHNC5jcmwwIAYDVR0gBBkwFzAIBgZngQwBBAIwCwYJ
# YIZIAYb9bAcBMA0GCSqGSIb3DQEBCwUAA4ICAQB9WY7Ak7ZvmKlEIgF+ZtbYIULh
# sBguEE0TzzBTzr8Y+8dQXeJLKftwig2qKWn8acHPHQfpPmDI2AvlXFvXbYf6hCAl
# NDFnzbYSlm/EUExiHQwIgqgWvalWzxVzjQEiJc6VaT9Hd/tydBTX/6tPiix6q4XN
# Q1/tYLaqT5Fmniye4Iqs5f2MvGQmh2ySvZ180HAKfO+ovHVPulr3qRCyXen/KFSJ
# 8NWKcXZl2szwcqMj+sAngkSumScbqyQeJsG33irr9p6xeZmBo1aGqwpFyd/EjaDn
# mPv7pp1yr8THwcFqcdnGE4AJxLafzYeHJLtPo0m5d2aR8XKc6UsCUqc3fpNTrDsd
# CEkPlM05et3/JWOZJyw9P2un8WbDQc1PtkCbISFA0LcTJM3cHXg65J6t5TRxktcm
# a+Q4c6umAU+9Pzt4rUyt+8SVe+0KXzM5h0F4ejjpnOHdI/0dKNPH+ejxmF/7K9h+
# 8kaddSweJywm228Vex4Ziza4k9Tm8heZWcpw8De/mADfIBZPJ/tgZxahZrrdVcA6
# KYawmKAr7ZVBtzrVFZgxtGIJDwq9gdkT/r+k0fNX2bwE+oLeMt8EifAAzV3C+dAj
# fwAL5HYCJtnwZXZCpimHCUcr5n8apIUP/JiW9lVUKx+A+sDyDivl1vupL0QVSucT
# Dh3bNzgaoSv27dZ8/DCCBY0wggR1oAMCAQICEA6bGI750C3n79tQ4ghAGFowDQYJ
# KoZIhvcNAQEMBQAwZTELMAkGA1UEBhMCVVMxFTATBgNVBAoTDERpZ2lDZXJ0IElu
# YzEZMBcGA1UECxMQd3d3LmRpZ2ljZXJ0LmNvbTEkMCIGA1UEAxMbRGlnaUNlcnQg
# QXNzdXJlZCBJRCBSb290IENBMB4XDTIyMDgwMTAwMDAwMFoXDTMxMTEwOTIzNTk1
# OVowYjELMAkGA1UEBhMCVVMxFTATBgNVBAoTDERpZ2lDZXJ0IEluYzEZMBcGA1UE
# CxMQd3d3LmRpZ2ljZXJ0LmNvbTEhMB8GA1UEAxMYRGlnaUNlcnQgVHJ1c3RlZCBS
# b290IEc0MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAv+aQc2jeu+Rd
# SjwwIjBpM+zCpyUuySE98orYWcLhKac9WKt2ms2uexuEDcQwH/MbpDgW61bGl20d
# q7J58soR0uRf1gU8Ug9SH8aeFaV+vp+pVxZZVXKvaJNwwrK6dZlqczKU0RBEEC7f
# gvMHhOZ0O21x4i0MG+4g1ckgHWMpLc7sXk7Ik/ghYZs06wXGXuxbGrzryc/NrDRA
# X7F6Zu53yEioZldXn1RYjgwrt0+nMNlW7sp7XeOtyU9e5TXnMcvak17cjo+A2raR
# mECQecN4x7axxLVqGDgDEI3Y1DekLgV9iPWCPhCRcKtVgkEy19sEcypukQF8IUzU
# vK4bA3VdeGbZOjFEmjNAvwjXWkmkwuapoGfdpCe8oU85tRFYF/ckXEaPZPfBaYh2
# mHY9WV1CdoeJl2l6SPDgohIbZpp0yt5LHucOY67m1O+SkjqePdwA5EUlibaaRBkr
# fsCUtNJhbesz2cXfSwQAzH0clcOP9yGyshG3u3/y1YxwLEFgqrFjGESVGnZifvaA
# sPvoZKYz0YkH4b235kOkGLimdwHhD5QMIR2yVCkliWzlDlJRR3S+Jqy2QXXeeqxf
# jT/JvNNBERJb5RBQ6zHFynIWIgnffEx1P2PsIV/EIFFrb7GrhotPwtZFX50g/KEe
# xcCPorF+CiaZ9eRpL5gdLfXZqbId5RsCAwEAAaOCATowggE2MA8GA1UdEwEB/wQF
# MAMBAf8wHQYDVR0OBBYEFOzX44LScV1kTN8uZz/nupiuHA9PMB8GA1UdIwQYMBaA
# FEXroq/0ksuCMS1Ri6enIZ3zbcgPMA4GA1UdDwEB/wQEAwIBhjB5BggrBgEFBQcB
# AQRtMGswJAYIKwYBBQUHMAGGGGh0dHA6Ly9vY3NwLmRpZ2ljZXJ0LmNvbTBDBggr
# BgEFBQcwAoY3aHR0cDovL2NhY2VydHMuZGlnaWNlcnQuY29tL0RpZ2lDZXJ0QXNz
# dXJlZElEUm9vdENBLmNydDBFBgNVHR8EPjA8MDqgOKA2hjRodHRwOi8vY3JsMy5k
# aWdpY2VydC5jb20vRGlnaUNlcnRBc3N1cmVkSURSb290Q0EuY3JsMBEGA1UdIAQK
# MAgwBgYEVR0gADANBgkqhkiG9w0BAQwFAAOCAQEAcKC/Q1xV5zhfoKN0Gz22Ftf3
# v1cHvZqsoYcs7IVeqRq7IviHGmlUIu2kiHdtvRoU9BNKei8ttzjv9P+Aufih9/Jy
# 3iS8UgPITtAq3votVs/59PesMHqai7Je1M/RQ0SbQyHrlnKhSLSZy51PpwYDE3cn
# RNTnf+hZqPC/Lwum6fI0POz3A8eHqNJMQBk1RmppVLC4oVaO7KTVPeix3P0c2PR3
# WlxUjG/voVA9/HYJaISfb8rbII01YBwCA8sgsKxYoA5AY8WYIsGyWfVVa88nq2x2
# zm8jLfR+cWojayL/ErhULSd+2DrZ8LaHlv1b0VysGMNNn3O3AamfV6peKOK5lDGC
# A3YwggNyAgEBMHcwYzELMAkGA1UEBhMCVVMxFzAVBgNVBAoTDkRpZ2lDZXJ0LCBJ
# bmMuMTswOQYDVQQDEzJEaWdpQ2VydCBUcnVzdGVkIEc0IFJTQTQwOTYgU0hBMjU2
# IFRpbWVTdGFtcGluZyBDQQIQBUSv85SdCDmmv9s/X+VhFjANBglghkgBZQMEAgEF
# AKCB0TAaBgkqhkiG9w0BCQMxDQYLKoZIhvcNAQkQAQQwHAYJKoZIhvcNAQkFMQ8X
# DTIzMDgyMjEwMTkyM1owKwYLKoZIhvcNAQkQAgwxHDAaMBgwFgQUZvArMsLCyQ+C
# Xc6qisnGTxmcz0AwLwYJKoZIhvcNAQkEMSIEIKDQHHgH+3J050KyfpVnn/A9n8el
# 0XYiDvyVnsmFKysQMDcGCyqGSIb3DQEJEAIvMSgwJjAkMCIEINL25G3tdCLM0dRA
# V2hBNm+CitpVmq4zFq9NGprUDHgoMA0GCSqGSIb3DQEBAQUABIICAH+6ddg4xBCV
# Gw2flYq10v/omJtLAMKI69iGZNCDK0cNJ7SrhqUwJmNOfEAN9/zLbtYt35Q8eRXm
# g327vVsd9FPvmVuH6Q0zsDpXuRwbgZe5RIQ7QO+/8sxcHtQ7wrsy2eS1l9X80PP5
# 4J40pGORpznD4jYVzKXDAkEXubNYqVBdzm+nmb05LBcpUJvAs+Ir9zAbX/W0y0jx
# VEx/Ib2ST1NJaGwU6b9hWK5MJfXmtZL1mB2D42YzOe4LeQsLE1ex2tRFo2Skn+16
# LqcPMdvMOnXibb57TlCtDemvBNfQXxuNK1sM7ttaOGH5FkC5CRfymbdE5nqbGnbl
# JrO+if5/qcPtVIkvsNy+l+5ydE6zH4rQ8iRynrcIBczwTJEvpFgmmXyGVOd0yOAz
# hTrV3+xF7aji/0fMgNVoMpt5QcZxMKbUUhMMjEAKilra6UXKOkEhyz+AemsUcFXK
# tHLCEl8GCoHoiVZAniAsMPsx/zWT7KXjhntZ7AiVNOvw2BEQx2oqfhYN7AVZTQKN
# YdyC5+z+iUOvSgzIodzRjHqK+S3iKn4v+zI+a0l/JrYCtE3+SRrnnm32Wmv2H3qh
# dmVsIN51M8eoUnwmOwdIqiRBWHNeDRx95WU1IeGk1RD7ywKe53+TimAKIdW5bBxL
# mC3TL3FbOXm09+e+pzFJPTuA/+kHS7Mg
# SIG # End signature block
