name: Code_signing

# Controls when the workflow will run
on:
  push:
    tags:
        - 'v*'
      
jobs:
  release:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [windows-latest]
        
    steps:

        - name: Check out Git repository
          uses: actions/checkout@v3.5.3
          with:
            sparse-checkout: |
              *.ps1
            sparse-checkout-cone-mode: false          
          
        - name: List Checkout
          run: |
            dir

        - name: Setup Certificate
          run: |
            echo "${{ secrets.SM_CLIENT_CERT_FILE_B64 }}" | base64 --decode > /d/Certificate_pkcs12.p12
            cat /d/Certificate_pkcs12.p12
          shell: bash

          
        - name: Set variables
          id: variables
          run: |
            #echo "::set-output name=version::${GITHUB_REF#refs/tags/v}"
            echo "SM_HOST=${{ secrets.SM_HOST }}" >> "$GITHUB_ENV"
            echo "SM_API_KEY=${{ secrets.SM_API_KEY }}" >> "$GITHUB_ENV"
            echo "SM_CLIENT_CERT_FILE=D:\\Certificate_pkcs12.p12" >> "$GITHUB_ENV"
            echo "SM_CLIENT_CERT_PASSWORD=${{ secrets.SM_CLIENT_CERT_PASSWORD }}" >> "$GITHUB_ENV"
            echo "SM_CODE_SIGNING_CERT_SHA1_HASH=${{ secrets.SM_CODE_SIGNING_CERT_SHA1_HASH }}" >> "$GITHUB_ENV"
            echo "C:\Program Files (x86)\Windows Kits\10\App Certification Kit" >> $GITHUB_PATH
            echo "C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8.1 Tools" >> $GITHUB_PATH
            echo "C:\Program Files\DigiCert\DigiCert One Signing Manager Tools" >> $GITHUB_PATH
          shell: bash
          
          
        - name: Setup client tools - SSM KSP on windows latest
          run: |
            curl -X GET  https://demo.one.digicert.com/signingmanager/api-ui/v1/releases/smtools-windows-x64.msi/download -H "x-api-key:%SM_API_KEY%" -o smtools-windows-x64.msi
            msiexec /i smtools-windows-x64.msi /quiet /qn
            smksp_registrar.exe list
            smctl.exe keypair ls
            C:\Windows\System32\certutil.exe -csp "DigiCert Signing Manager KSP" -key -user
            smksp_cert_sync.exe
          shell: cmd
          
        - name:  Remove MSI from Folder
          run: |
            dir
            del smtools-windows-x64.msi
            dir
          shell: cmd

        - name: Signing using Signtool
          run: |
            #signtool.exe sign /sha1 ${{ secrets.SM_CODE_SIGNING_CERT_SHA1_HASH }} /tr http://timestamp.digicert.com /td SHA256 /fd SHA256 ".\\*.ps1"          
            #signtool.exe sign /sha1 "6288d4b40bb873d82aa0007ab19ca6fb77ddfa48" /tr http://timestamp.digicert.com /td SHA256 /fd SHA256 "04 - Split PFX to Key and Cert.ps1"
            #smctl sign --fingerprint ${{ secrets.SM_CODE_SIGNING_CERT_SHA1_HASH }} --input .
            smctl sign --keypair-alias=CoolCats_Test_02 --input="."

        - name: List Checkout
          run: |
            dir

        - name: Upload artifacts
          uses: actions/upload-artifact@v3.1.2
          with:
            name: ${{ matrix.os }}
            path: .\\*.ps1
